# check dependency
dependency_exists() {
    type "$1" > /dev/null 2>&1
}

# Autoload the ZSH completion to avoid kubectl autocomplete error
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit

# Add Go paths to PATH
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOPATH
export PATH=$PATH:$GOBIN

# Use oh-my-zsh
export ZSH="/Users/darrenjones/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# Enable oh-my-zsh plugins
plugins=(git autojump kubectl aws)

# Init oh-my-zsh
source $ZSH/oh-my-zsh.sh

# HSTR configuration
export HISTFILE=~/.zsh_history              # set the history file

if dependency_exists hstr; then
  setopt histignorespace                      # skip cmds w/ leading space from history
  export HSTR_CONFIG=prompt-bottom,hide-help,raw-history-view,hicolor
  bindkey -s "\C-r" "\C-a hstr -- \C-j"       # bind hstr to Ctrl-r (for Vi mode check doc)
fi

# kubePS1 config
if [ -f /usr/local/opt/kube-ps1/share/kube-ps1.sh ]; then
  source /usr/local/opt/kube-ps1/share/kube-ps1.sh
  export KUBE_PS1_SYMBOL_ENABLE=false
  PS1='$(kube_ps1)'$PS1
fi



if dependency_exists tmux; then
  # tmux all the time
  [ -z "$TMUX"  ] && { tmux attach || exec tmux new-session && exit;}
fi

# Add aliases
if [ -f ~/.aliases ]; then
  source ~/.aliases
fi

# Add env secrets
if [ -f ~/.env_private ]; then
  source ~/.env_private
fi
